name: Test rcpputils
on:
  pull_request:
  push:
    branches:
      - master
      - seanyen**
  schedule:
    # Run every hour. This helps detect flakiness,
    # and broken external dependencies.
    - cron:  '0 * * * *'

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
          os: [ubuntu-latest, windows-latest]
    steps:
    - uses: seanyen/setup-ros@seanyen/cppcheck
    - uses: ros-tooling/action-ros-ci@master
      with:
        package-name: rcpputils
    - uses: actions/upload-artifact@master
      with:
        name: colcon-logs
        path: ros_ws/log

